### ISSUE TITLE
안녕하세요 실행시 에러가 생겨서 질문드립니다. 

### ISSUE THREAD

**Issue by rlaalstn1504** [affjljoo3581/Job-Recommend-Competition#1]

**Comment by rlaalstn1504** [comment]
안녕하세요 좋은 코드 공유해주셔서 감사합니다. 
실행을 위해 preprosess.sh 파일에서 
python preprocessing/preprocess.py res/train/KNOW_2017.csv res/test/KNOW_2017_test.csv --data_type=2017 --use_simcse_embeddings 명령을 실행하는데 에러가 생겼습니다.  
에러 메시지는 다음과 같습니다. 

 File "D:\python\Job-Recommend-Competition-main\preprocessing\text_embedding.py", line 29, in get_text_embeddings_from_simcse
    from data.dataloader import convert_to_tensor, example_model_setting
ModuleNotFoundError: No module named 'data'  

해결 방법을 요청드려도 될까요?

**Comment by affjljoo3581** [comment]
안녕하세요. `--use_simcse_embedding`은 한국어 SimCSE 모델을 사용하여 문장 임베딩을 생성하는 옵션입니다. 따라서 SimCSE 코드 및 가중치 파일이 필요한데요. `--simcse_package_dir`와 `--simcse_model_ckpt`로 지정해줄 수 있습니다.

해당 오류의 경우 SimCSE 내 data 모듈을 찾지 못해서 발생한 것으로 보입니다. 되도록이면 [해당 문서](https://github.com/affjljoo3581/Job-Recommend-Competition/blob/main/REPRODUCTION.md)를 참고하여 진행해주시길 바랍니다.

**Comment by rlaalstn1504** [comment]
감사합니다 해결했습니다!
